label S_03_K:
    scene TESTSCENE with Dissolve(2.5)
    "I'm resting at my desk, my head buried in my arms."
    "Almost dozing off, with only the sound of the air-conditioning to keep my company."
    "So sleepy…"
    "I must have set my alarm too early to have arrived here this soon. Classes won't even start for another half-hour."
    "If only I was back in my bed, surrounded by softness from every direction…"
    "If only…"
    "..."
    "The sound of the door being opened pulls me forcefully back to the present."
    "I raise my head and blink, bleary-eyed, at the form entering the classroom."
    "It's roughly Kokoro-shaped and of approximately Kokoro-height."
    
    kura "Kokoro?"
    show kura hmm:
        yanchor 1.0 ypos 1080+300 xalign 0.4
    show kokoro smile:
        yanchor 1.0 ypos 1080+300 xalign 0.6
    kokoro "Hi hi!"
    kura hmm "You're here early…"
    kokoro laugh "Well, so are you!"
    "I groan as she sits beside me and sets down her things. She's right, and I regret it."
    kura frown "Believe me, I wouldn't be here this early if I could help it."
    kokoro smile "That's no way to talk! The early bird gets the worm, you know."
    kura "I don't even like worms."
    kokoro "Well, you should. They're very high in protein."
    kura frown "Ew…"
    kokoro "And anyway, it's just a metaphor!"
    kura mad "If it's just a metaphor, why does the protein content matter?"
    kokoro "You ask too many questions, Kura!"
    kura frown "Ugh…"
    "Just then, Kokoro takes her mug from her bag and sets it on the table."
    "It's an adorable accessory she's always carrying around: garishly pink and covered in cartoon flowers."
    "Half the time she doesn't even bother to fill it up. It's just there to spruce up her desk."
    "But today, she's come prepared."
    "She heaves a huge thermos from her backpack and twists open the cap."
    "The scent of earl grey wafts toward me."
    kura hmm "Mm…"
    kokoro smile "Do you want some, Kura?"
    kura "No, it's okay. It just smells nice."
    kokoro smile_open "Okay!"
    "I set my head back down in my arms and close my eyes, trying to turn the smell into a lullaby."
    kokoro neutral "Kura, what are you doing?"
    kura "Mmf…"
    kura "Sleeping."
    kokoro smile "Kura~ You can't sleep now! We have class!"
    kura "Not for another twenty minutes."
    kokoro "But then you'll be tired when it starts!"
    kura frown "I'm already tired, Kokoro."
    kokoro frown "Hmph."
    "Oh, no. I can hear the pout in her voice. The patented Kokoro pout."
    "I relent and lift my head again."
    kura hmm "Okay, okay, I'm back up! Just don't-"
    "The words catch in my throat as I notice Kokoro's mug."
    "It's exactly where she left it, and filled with steaming tea."
    "But it's {i}blue{/i}."
    "It's still got the same floral pattern, but all the colors look like they've been inverted. Like a film negative."
    kura frown "Kokoro… your mug…"
    kokoro "My mug?"
    kokoro "Oh! Did you want some?"
    kura hmm "No, I just… it's blue."
    kokoro "..."
    kokoro grin "Well, of course it is! It's a blue mug, silly."
    kura "But it was just pink."
    kokoro neutral "Pink?"
    kokoro "Kura, I've never had a pink mug."
    kura frown "What are you talking about? You always have a pink mug you carry around, just like that one, except it's {i}pink{/i}."
    "Kokoro frowns at me for a moment, then breaks into a sympathetic smile."
    kokoro "You really are tired, Kura."
    kura "I'm not {i}that{/i} tired, I know what I saw. You took the mug out and it was pink. And now it's blue."
    kura "Your mug just… changed colors."
    kura "It was like magic."
    kokoro "Oh, Kura, don't be silly!"
    kokoro smile "You know that's not possible. Magic isn't real."
    kura "But I just saw it. Didn't you?"
    "She shrugs and starts to scribble in one of her notebooks."
    kokoro grin "I just see my mug. Blue like it always is."
    kokoro grin2 "You're probably still half-asleep."
    kokoro neutral "Do you know about sleep paralysis?"
    kura "That's when you wake up but you can't move, right?"
    kokoro "I watched something about it on TV once. Your brain still hallucinates when it happens, so you see things that aren't real."
    kokoro "Sometimes even if you aren't paralyzed, you hallucinate the things because your brain is half-dreaming."
    kokoro "You were probably just half-dreaming when I took out the mug, Kura. Like you said, it's early."
    kokoro smile "So you hallucinated the pink, and now you're not half-dreaming anymore so you see that it's blue."
    kura "Yeah, but…"
    kokoro smile_open "Don't worry. You'll be fully awake by the time class starts."
    kokoro smile "Which is good, because we'll need your help for our assignments!"
    kura hmm "Yeah…"
return
