label S_07_K:
    #TODO: Add sprite, BG and Music direction
    "I turn the corner."
    "There's Kokoro, staring at a wall that's shattered like glass, a blank smile on her face."
    "Shards of blue and red flutter around her like butterflies. It's disconcerting to see."
    "The impossible things in this hallway pry at some deep, hidden fear."
    "Fear that my perception was wrong all along."
    kura "Kokoro!"
    "She ignores me."
    kokoro "It's wonderful."
    "Her face is wet with tears."
    kura "What's wrong, Kokoro?"
    kokoro "Huh? What do you mean?"
    "She leans back slightly, admiring the view."
    kura "You shouldn't be so close to that! It's dangerous!"
    kokoro "You're wrong. Look."
    "Frustration wells up in my body."
    kokoro "It's just like I remember."
    kura "What? What are you talking about?"
    kokoro "Don't you think it's beautiful?"
    kura "Beautiful? Kokoro, I don't understand what you're saying!"
    kokoro "Be calm, Kura."
    "She takes a deep breath, closing her eyes and savouring the sensation."
    kokoro "Everything is fine."
    "I take a determined step forward."
    kura "It's not! Can't you see what's in front of you?"
    "As a beaming smile stretches across Kokoro's face, a giggle escapes her open mouth."
    kura "Can't you see what's happening, Kokoro?"
    kokoro "Of course I can."
    "All right. Enough of this."
    kokoro "And it's amazing."
    kokoro "Breathtaking, even."
    "I grab Kokoro's hand and pull hard in an attempt to move us away from the wall."
    "She slips her hand from my grasp with ease."
    kura "Grh!"
    kura "I don't understand!"
    kura "All this time you deluded yourself! Now you see what's really happening you think it's beautiful!?"
    kura "..."
    kura "Come on."
    "I grab her wrist once more."
    "She attempts to free herself again, but this time I hold on tighter."
    "Her dumb smile changes to a frown."
    kokoro "Let me go."
    kura "We have to get back to the others."
    kokoro "Let go!"
    "She grabs at my hand with her free one, digging her nails into my skin."
    kura "Ow! What the fuck, Kokoro?"
    "She doesn't respond, instead squeezing harder."
    kura "Grh!"
    "Instinct kicks in and I attempt to push Kokoro away from me."
    "Anger fills my body."
    "All this time she denied the absurd happenings going on around us."
    "Every time. Dismissing us as though we're stupid for believing it."
    "I use my free hand to reach up to Kokoro's head."
    "I see red."
    "My fist filled with hair, I pull."
    "Kokoro's head snaps back as a chunk of hair is pulled free from her head."
    "I grit my teeth. That's what you get."
    kokoro "?"
    "Kokoro attempts to grab her hair a few times, as if to confirm that it's gone."
    kokoro "!?"
    "Her eyes become dull."
    kokoro "Fine."
    kokoro "F-fine."
    "She takes a few staggered steps backwards, tears welling in her eyes."
    "My anger begins to pass as I see what I've done."
    kura "Ah."
    kura "Kokoro..."
    "She trips backwards and has to reach a hand out to a nearby door to support herself."
    kura "Kokoro?"
    "Wind blows through the quiet hallway, and I hear a soft crinkling all around."
    "Kokoro slowly waves her hand in front of her face, as if examining the fact she has hands."
    kura "Are you okay?"
    kokoro "I..."
    "She's interrupted by a low rumbling coming from under the door."
    "We both focus our eyes on the narrow gap beneath the door."
    "As we watch, a black fog pours from the crack."
    kura "Oh no..."
    "I stagger backward as cold, black liquid starts to pool around our feet."
    kura "We have to go!"
    "She stands up straight, removing her hand from the wall, and the hallway behind her twists uncomfortably."
    "Kokoro stands like a statue in comparison, her expression unchanging as the cold black fog laps at my feet."
    "So cold."
    kura "Kokoro!"
    "Gravity pulls at my body from all angles."
    "I try to take a step, but the tar-like liquid, now spilling from under the door in waves, stops me."
    "Black shapes swoop through the hallway, replacing the blue and red ones that populated the air a few moments ago."
    "Kokoro smiles sickeningly, before her smile turns to a grin with a giggle."
    kokoro "It's really strange... just like I remember it."
    "My legs sting as the cold liquid rises higher."
    kokoro "Not just like it, not just similar... ."
    kokoro "It's exactly as I remember it. Right down to the smallest detail."
    kura "What are you talking about!?"
    "My frustration tastes like blood in my mouth."
    kokoro "You should know, Kura."
    kokoro "Don't you remember, too?"
    "I grasp at Kokoro. Maybe we can still get out of this."
    "She's wet to the touch. Soaking wet and freezing cold."
    "I shake her shoulders, or at least try, but the motion doesn't make any sense."
    kura "Snap out of it!"
    "Shadows pour from Kokoro's eyes in the place of tears and her gaze is locked onto me."
    kura "Come on!"
    "I shake her again. The motion makes my head hurt."
    "The whistling I hadn't noticed in my ears until now has quickly become deafening."
    "I grab at Kokoro, desperately trying to hold on to what's left, but my body feels like it's being crushed, every movement taking impossible effort."
    "Shadow still pours from Kokoro's eyes. Her smile has vanished, replaced with a frown."
    kura "Kokoro?"
    kokoro "I'm here, Kura."
    kokoro "Don't worry."
    "The shadows in the hallway loom towards us."
    kokoro "Ev... Everything will be fine."
    "She tries to smile, but can't."
    "The shadows pool at our feet. I try to get up, but I'm pinned to the floor."
    kokoro "Everything will be fine!"
    "Kokoro's tone is uneasy, miles away from the strange calm moments ago."
    "The shadows splash against my face."
    kokoro "It has to be, right? It has to be fine?"
    "She holds her arms before her face. Skin and muscle fall away from bone."
    kokoro "Right!? Kura?"
    "I can't bring myself to speak."
    kokoro "RIGHT!?"
    "More shadows pool behind Kokoro, her form outlined with endless darkness."
    kokoro "It h-has to be fine."
    kokoro "Everything is f-f-fine."
    "The shadows grab at her body. Thousands of hands, all pulling at once."
    kokoro "Evr... Gshr... fiine."
    kokoro "Fiiiine."
    kokoro "F..."
    kokoro "Fi..."
    "She tries once more to form that word and fails."
    "Anguish flashes across her face."
    kokoro "Fffff..."
    "I close my eyes, but the grasping shadow-hands persist in my vision. There's no escape."
    "This is the end."
return
