label S_07_K:
    show kura frown:
        yanchor 1.0 ypos 1080+300 xalign 0.3
    "The classroom is completely empty now."
    "To the side is Kokoro, staring at a wall that's shattered like glass, a blank smile on her face."
    "Shards of blue and red flutter around her like butterflies. It's disconcerting to see."
    "The impossible things in this hallway pry at some deep, hidden fear."
    "Fear that my perception was wrong all along."
    show kokoro shock2:
        yanchor 1.0 ypos 1080+300 xalign 0.3
    kura mad "Kokoro!"
    "She ignores me."
    kokoro "It's wonderful."
    "Her face is wet with tears."
    kura frown "What's wrong, Kokoro?"
    kokoro smile "Huh? What do you mean?"
    "She leans back slightly, admiring the view."
    kura "You shouldn't be so close to that! It's dangerous!"
    kokoro smile_open "You're wrong. Look."
    "Frustration wells up in my body."
    kokoro "It's just like I remember."
    kura frown "What? What are you talking about?"
    kokoro grin "Don't you think it's beautiful?"
    kura mad "Beautiful? Kokoro, I don't understand what you're saying!"
    kokoro neutral "Be calm, Kura."
    "She takes a deep breath, closing her eyes and savoring the sensation."
    kokoro shock2 "Everything is fine."
    "I take a determined step forward."
    kura cry_mad "It's not! Can't you see what's in front of you?"
    "As a beaming smile stretches across Kokoro's face, a giggle escapes her open mouth."
    kura "Can't you see what's happening, Kokoro?"
    kokoro smile_open  "Of course I can."
    "All right. Enough of this."
    kokoro "And it's amazing."
    kokoro grin2 "Breathtaking, even."
    "I grab Kokoro's hand and pull hard in an attempt to move us away from the wall."
    "She slips her hand from my grasp with ease."
    kura cry_sad "Grh!"
    kura "I don't understand!"
    kura cry_mad "All this time you deluded yourself! Now you see what's really happening you think it's beautiful!?"
    kura frown "..."
    kura cunning2 "Come on."
    "I grab her wrist once more."
    "She attempts to free herself again, but this time I hold on tighter."
    "Her dumb smile changes to a frown."
    kokoro shock2 "Let me go."
    kura "We have to get back to the others."
    kokoro frown "Let go!"
    "She grabs at my hand with her free one, digging her nails into my skin."
    kura mad "Ow! What the fuck, Kokoro?"
    "She doesn't respond, instead squeezing harder."
    kura "Grh!"
    "Instinct kicks in and I attempt to push Kokoro away from me."
    "Anger fills my body."
    "All this time she denied the absurd happenings going on around us."
    "Every time. Dismissing us as though we're stupid for believing it."
    "I use my free hand to reach up to Kokoro's head."
    "I see red."
    "My fist filled with hair, I pull."
    "Kokoro's head snaps back as a chunk of hair is pulled free from her head."
    "I grit my teeth. That's what you get."
    kokoro frown "?"
    "Kokoro attempts to grab her hair a few times, as if to confirm that it's gone."
    kokoro "!?"
    "Her eyes become dull."
    kokoro shock "Fine."
    kokoro shock2 "F-fine."
    "She takes a few staggered steps backwards, tears welling in her eyes."
    "My anger begins to pass as I see what I've done."
    kura frown "Ah."
    kura "Kokoro..."
    "She trips backwards and has to reach a hand out to a nearby door to support herself."
    kura cry_sad "Kokoro?"
    "Wind blows through the quiet hallway, and I hear a soft crinkling all around."
    "Kokoro slowly waves her hand in front of her face, as if examining the fact she has hands."
    kura "Are you okay?"
    kokoro neutral "I..."
    "She's interrupted by a low rumbling coming from under the door."
    "We both focus our eyes on the narrow gap beneath the door."
    "As we watch, a black fog pours from the crack."
    kura frown "Oh no..."
    "I stagger backward as cold, black liquid starts to pool around our feet."
    kura mad "We have to go!"
    "She stands up straight, removing her hand from the wall, and the hallway behind her twists uncomfortably."
    "Kokoro stands like a statue in comparison, her expression unchanging as the cold black fog laps at my feet."
    "So cold."
    kura "Kokoro!"
    "Gravity pulls at my body from all angles."
    "I try to take a step, but the tar-like liquid, now spilling from under the door in waves, stops me."
    "Black shapes swoop through the hallway, replacing the blue and red ones that populated the air a few moments ago."
    "Kokoro smiles sickeningly, before her smile turns to a grin with a giggle."
    kokoro smile "It's really strange... just like I remember it."
    "My legs sting as the cold liquid rises higher."
    kokoro "Not just like it, not just similar... ."
    kokoro smile_open "It's exactly as I remember it. Right down to the smallest detail."
    kura frown "What are you talking about!?"
    "My frustration tastes like blood in my mouth."
    kokoro "You should know, Kura."
    kokoro shock2 "Don't you remember, too?"
    "I grasp at Kokoro. Maybe we can still get out of this."
    "She's wet to the touch. Soaking wet and freezing cold."
    "I shake her shoulders, or at least try, but the motion doesn't make any sense."
    kura mad "Snap out of it!"
    "Shadows pour from Kokoro's eyes in the place of tears and her gaze is locked onto me."
    kura "Come on!"
    show kokoro frown
    "I shake her again. The motion makes my head hurt."
    "The whistling I hadn't noticed in my ears until now has quickly become deafening."
    "I grab at Kokoro, desperately trying to hold on to what's left, but my body feels like it's being crushed, every movement taking impossible effort."
    "Shadow still pours from Kokoro's eyes. Her smile has vanished, replaced with a frown."
    kura "Kokoro?"
    kokoro "I'm here, Kura."
    kokoro "Don't worry."
    "The shadows in the hallway loom towards us."
    kokoro smile "Ev... Everything will be fine."
    "She tries to smile, but can't."
    "The shadows pool at our feet. I try to get up, but I'm pinned to the floor."
    kokoro "Everything will be fine!"
    "Kokoro's tone is uneasy, miles away from the strange calm moments ago."
    "The shadows splash against my face."
    kokoro smile2 "It has to be, right? It has to be fine?"
    "She holds her arms before her face. Skin and muscle fall away from bone."
    kokoro "Right!? Kura?"
    "I can't bring myself to speak."
    kokoro shock2 "RIGHT!?"
    "More shadows pool behind Kokoro, her form outlined with endless darkness."
    kokoro "It h-has to be fine."
    kokoro shock "Everything is f-f-fine."
    "The shadows grab at her body. Thousands of hands, all pulling at once."
    kokoro "Evr... Gshr... fiine."
    kokoro shock2 "Fiiiine."
    kokoro "F..."
    kokoro "Fi..."
    "She tries once more to form that word and fails."
    "Anguish flashes across her face."
    kokoro smile "Fffff..."
    show kokoro at transform_hide:
        hide kokoro
    "I close my eyes, but the grasping shadow-hands persist in my vision. There's no escape."
    show kura at transform_hide:
        hide kura
    "This is the end."

    $ persistent.kokoroClear = True

return
