label S_03_U:
    scene TESTSCENE with Dissolve(2.5)
    "The librarian never did come, but Utagu and I decided between ourselves that it would be fine to take the books anyway."
    "We'd just let staff know we checked them out whenever we saw them next."
    "It's not a big deal. Probably."
    show kokoro smile:
        yanchor 1.0 ypos 1080+300 xalign 0.3
    show kura hmm:
        yanchor 1.0 ypos 1080+300 xalign -0.1
    show utagu uhh:
        yanchor 1.0 ypos 1080+300 xalign 0.7
    show oni neutral:
        yanchor 1.0 ypos 1080+300 xalign 1.2
    "The next day, we're back in class with Oni and Kokoro, whittling away the time with idle talk."
    "I watch the clock tick by and drum my fingers on my desk, utterly bored."
    "It never feels like we do anything in class. Doesn't that defeat the purpose of school?"
    "I'm here to learn things, but I don't feel like I have been."
    "I feel like we do the same nothing every day. Over and over again."
    "The same sleepy mornings and lazy afternoons spent aimlessly in this classroom between the four of us."
    "It's pointless."
    "Whatever our curriculum is, it clearly needs fixing if all I'm doing is musing here with a sense of deja vu day after day."
    "My eyes drift over to Kokoro, who's talking animatedly at Oni. The latter is looking back at her with a sort of subdued, fond expression. It's sweet."
    kokoro "I was trying to decide if I should add the chili before or after stirring."
    oni "Right."
    kokoro smile_open "But I decided I could just do both! So I put some chili in, gave it a stir, and put in a bit more."
    kokoro "And it came out just the way I wanted!"
    kokoro smile "Of course, I still don't know which way is the right way, but it doesn't matter."
    kokoro "As long as it tastes good, who cares."
    oni smile "Of course. As long as it tastes good."
    "Meanwhile, Utagu is examining her arm, which is bandaged up. It's been that way for a little while, now that I think about it."
    "She seems anxious."
    kura hmm"What's up, Utagu?"
    utagu uhh "What?"
    kura "You look distracted."
    utagu "I am, yeah…"
    kura "So, what's up?"
    utagu "I don't remember how I got this, actually."
    "She indicated her arm as she says it, and gives me a distressed frown."
    "She worries way too much, this one."
    kura "Oh, that's easy, Utagu."
    kura "You just…"
    kura "Um…"
    "Actually, how did that happen?"
    "I'm sure I knew the story once. But it's slipped away from me in the moment."
    "I felt the answer on the tip of my tongue, and then it was gone."
    "It's like I'm scraping the corners of my memory for something I know was there, but I can't find it."
    oni "You fell. Remember?"
    "And suddenly, Oni's chiming in. She must have overheard Utagu's confusion."
    "She's watching Utagu a with a grim, concerned frown."
    "Something about her answer triggers a faint memory in my head."
    kura "Oh, that's right. You fell off…"
    oni "Your bike."
    oni "You were biking to school one day and lost control because of a poorly placed pebble."
    oni "You landed on that arm and took a bit of a hit to the head."
    oni "I wouldn't be surprised if that's why you're having trouble remembering it."
    "Utagu takes the words in, her mouth slightly open in bewilderment. It's like what Oni's saying isn't even registering to her."
    utagu "I fell?"
    oni "Mhm."
    utagu "Off my bike?"
    oni "Yes."
    utagu "I don't remember."
    oni "Like I said, you also took a hit to the head, so I'm not surprised."
    oni "It was a rough fall."
    utagu "How long ago was this?"
    oni "It must have been last week. I don't remember the exact day, but you showed up late to class with that bandage and we heard the story from someone who saw you fall."
    utagu "Oh…"
    kura "Who was it who saw her fall?"
    oni "Some girl. A classmate. Her name was 'Mei' or something."
    kura "Mei? What does she look like?"
    oni "Like anyone else, I guess? Dark hair, average height?"
    kura "Is she in any of our classes?"
    oni "No, I don't think so."
    oni "Why are you interrogating me, anyway? I'm just explaining what happened."
    oni "Who cares who saw Utagu fall. She fell, and that's why she's hurt."
    oni "And she hit her head, which is why she can't remember."
    "Oni spits those last few sentences with an irritated edge, her brow furrowed in frustration."
    "She turns to her notebook and starts to doodle, clearly done with our conversation."
    kokoro "She's right, you know."
    kokoro "You're worrying too much."
    kokoro "I'm sure Utagu will be fine. It sounds like a nasty fall, but with bandages like those it can't be too serious."
    kokoro "It will be okay."
    utagu "Yeah…"
    "And with that, we fall silent."
    "Kokoro opens up one of her books, and Utagu looks out the window, obviously daydreaming."
    "But as I mull over what Oni said, I can't shake the sense that something isn't right."
    "She was right. I was interrogating her, because the pieces weren't fitting together."
    "If Utagu fell on her head, that would explain why she can't remember."
    "But why can't I remember, either?"
    "Surely I'd have heard about this through the grapevine. Utagu's my friend. I'd have asked about the bandaged before."
    "But here I am, with no recollection of the sort. It's as if I'd only just learnt of her bandages today, even though Oni says they've been around for at least a week."
    "And I've never heard of this Mei person, who allegedly saw Utagu fall."
    "Her description doesn't ring any bells, either."
    "I don't want to think that Oni's lying, but I just can't get myself to buy the story."
    "Since when did Utagu even have a bike?"
    "I scratch my head and catch Oni looking at me out of the corner of her eye."
    "I offer her a weak smile and turn to my notebook, mind racing more than I would like."