label S_05_U:
    scene TESTSCENE with Dissolve(2.5)
    "It happens just as the bell rings to mark the end of class."
    "I'm putting my books away when I hear Utagu scream."
    "It's not a drawn-out noise. It crashes against my ears rather like glass shattering. Quick and punctuated."
    "She's standing by her desk, one hand at her mouth, the other pointing to the windows."
    "They're black."
    "Empty."
    "As if there's nothing behind them at all."
    "Somehow, the inside of the classroom is still lit, like the Sun is still out there, illuminating us."
    "But it's not."
    "It's gone."
    "Oni and Kokoro are looking too."
    "Kokoro appears unfazed, blinking the sight happily away, but Oni grimaces."
    "She doesn't look surprised. Only upset."
    utagu "Am I the only one seeing this?"
    "Utagu chokes out the words, rooted in her spot."
    "I shake my head."
    kura "I see it, too."
    "I walk up to the windows and lean forward, peering through."
    "It isn't just dark."
    "It's completely blank. There's nothing on the other side."
    "I raise a hand and press it against the glass."
    "In a blink, it all comes back."
    "The school courtyard fills in instantly. The clouds reappear, like they were never gone, and the Sun is back, though it doesn't add to the light in the room."
    "It's like the outside and the inside are totally separate."
    utagu "What the fuck was that?"
    "She's still standing in the same spot, pulling at her hair anxiously."
    utagu "Did you all see that?"
    utagu "It just disappeared!"
    utagu "What the fuck?"
    kokoro "I'm sure it's fine, Utagu."
    kokoro "Strange weather happens all the time."
    utagu "Kokoro, stop!"
    utagu "This isn't weather."
    utagu "This is…"
    utagu "It feels like the apocalypse. It feels like things are falling apart. It doesn't make any sense."
    utagu "{i}Did nobody else notice everything outside disappearing?!{\i}"
    kura "Utagu, take a breath."
    kura "We all noticed it, but I'm sure there's an explanation."
    kura "Oni?"
    "I call out her name not because I plan on believing her, but because she's at least presented us with explanations the last two times."
    "In fact, I'm very curious to see what she'll come up with this time."
    "Personally, I'm with Utagu."
    "But it wouldn't help to tell her that."
    "Oni sighs."
    oni "I think it's the new polarized window technology they're testing out."
    kura "Polarized windows?"
    oni "It's fancier than blinds. The windows can darken from either direction with an electrical current."
    oni "They must have been messing with the controls just now. They blacked them out from our direction, but not from outside, which is why all the light still made it in."
    oni "You happened to touch the glass right when they turned it off, Kura."
    "She delivers this explanation in the most nonchalant monotone, as though it ought to be obvious."
    "It sounds suspiciously rehearsed. It fits better than her previous explanations. Almost too well."
    kura "How do you know all this? Why are you always the one with the answers?"
    oni "I pay attention, Kura."
    oni "It shouldn't come as a surprise."
    oni "Kokoro doesn't have a care in the world. Utagu's taken a hit to the head. You're chronically absent-minded."
    oni "I'm the grounded one of us."
    oni "They made an announcement to the school about the windows during our last monthly assembly. I assume nobody else here was paying attention."
    "I don't even remember the assembly."
    "I want to press Oni on her story, but Utagu breaks down before I can say anything."
    utagu "But that doesn't make any sense!"
    utagu "I don't remember an assembly. I don't remember anything about polarized windows."
    utagu "{i}Nothing you've told me today sounds real, Oni{/i}"
    kura "Utagu, please."
    kura "I know this is weird, but there's no need to freak out."
    utagu "No need to freak out? {i}The outside just disappeared, Kura!{/i}"
    oni "Like I said, they're just-"
    utagu "Polarized windows? That none of us knew about until now?"
    oni "Well, I can't help it if I'm the only one-"
    utagu "{i}The only one who seems to think this is okay!{/i} That's who you are."
    utagu "Except Kokoro. But she never complains anyway."
    "Utagu tries to wipe away the tears now streaming down her face and balls her fists in frustration."
    utagu "This isn't like you, Oni."
    utagu "You're hiding something, and it scares me."
    utagu "Kura sees it too. I know she does."
    utagu "Isn't that right, Kura?"
    kura "I—well…"
    kura "I think a bunch of strange things are happening at once."
    kura "But… if you think about it, that's bound to happen."
    kura "We're going to have strange days when coincidences pile up."
    kura "Today is just one of those days."
    utagu "Today is just an unusually strange day? Is that really what you think."
    "It isn't."
    kura "It is."