label 06_U:
    scene TESTSCENE with Dissolve(2.5)
    #TODO
    kokoro "TEST SCRIPT"
    oni "TEST SCRIPT"
    utagu "TEST SCRIPT"
    kura "TEST SCRIPT"

    utagu "I want to believe you, Kura. I really do."
    kura "Why can't you?"
    utagu "I don't know. I just... can't."
    utagu "I feel wrong."
    kura "You feel wrong?"
    utagu "Yeah. Like I'm somewhere I'm not supposed to be. Or, I'm something I was never meant to be."
    utagu "I feel like I don't fit together."
    utagu "I feel like thirty pieces from thirty different puzzles mashed together."
    kura "Utagu, I..."
    kura "I don't know what to say."
    kura "I get that you're worried, and I get why. Believe me, I do."
    kura "But I think this will be okay. We'll be fine."
    kura "It's a little weird, what's been going on lately. I won't deny it."
    kura "But this is just another day. Another day at school. And tomorrow, another one will come. A better one."
    "Utagu doesn't meet my eye, but fixates on a spot on the floor, her voice tremulous."
    utagu "And what if it doesn't?"
    "I don't know what to say to this. But Kokoro speaks up to say it for me."
    kokoro "Don't be silly, Utagu. What's the point of thinking like that?"
    kokoro "If you expect tomorrow to be bad, of course it will be."
    kokoro "You can't spend your whole life worrying that things will get worse."
    "Utagu mumbles something in response, too quiet for Kokoro's ears, but just loud enough for mine."
    utagu "But what if I can?"
    "The moment passes uneasily. It seems like the clock on the wall ticks thrice for each second."
    "It must be the tension in the air."
    "Finally, Oni steps closer to us and speaks up."
    oni "Kura's right, Utagu."
    oni "It isn't worth worrying."
    oni "You can spend every second in anxiety. The best that gives you is a sick satisfaction the one time you're right."
    oni "The rest is just apprehension. It's not worth it."
    "Utagu glances up at her and gives a weak nod."
    "She blinks, as though to clear her thoughts for a second."
    utagu "Yeah..."
    utagu "You're probably right."
    "Apparently statisfied at this resolution, Kokoro withdraws to a nearby desk and starts fidgeting with the hem of her skirt."
    "Oni stays put, watching us with an unreadable expression."
    "I decide I should offer Utagu a few more words of comfort."
    "As a step closer, though, several things happen. Slowly, and yet, in an instant."
    "First, Utagu's eyes widen and her mouth drops. She points at the ground."
    "And then I look, too, and find myself staring into a widening gap in the floor, right at Utagu's feet."
    "Except that there's nothing behind this gap. No concrete or plumbing or foundation. Just an endless black."
    "I watch, immobilized, as pieces of the floor crumble at the edges and the hole grows larger."
    "Before I can offer the slightest reaction, it's beneath both of us."
    "I have a moment to look up and catch Oni's mesmerized, horrified gaze, fixed on us."
    "Then, I feel myself falling, though I can't see into what."
    "The classroom we were just in moves up out of our sight, and Oni and Kokoro move with it."
    "But Utagu's still here, with me, right next to me, suspended in the dark."
    "And, a second later, our surroundings materialize."
    "We aren't in the classroom anymore. Oni and Kokoro are gone. But we're still definitely somewhere in the school."
    "It looks like..."
    kura "The basement...?"
    "It was. There was no mistaking the distinctive colour of the walls and the musty scent of the place."
    kura "But how?"
    "I look to Utagu. She's frozen in place, mouth agape and brow contorted to an expression of horror."
    kura "Utagu?"
    "She bites her lip and turns to me in response. Tears start to stream down her face."
    utagu "What's going on, Kura?"
    utagu "What's happening?!"
    utagu "We were just with them! With Oni and Kokoro."
    utagu "And now we're here."
    utagu "This isn't just 'weird', Kura. This is all wrong."
    kura "I know, I just… I don't think-"
    utagu "Don't tell me to stay calm, Kura."
    utagu "Don't tell me not to panic. It's too late for that."
    utagu "Look at this!"

return
