label S_02_O:
    scene TESTSCENE with Dissolve(2.5)
    "…I wonder why Oni was so off just now."
    "She tends to keep personal matters to herself, and nobody here has really put any effort into asking how she’s doing."
    "I think it wouldn't hurt to check up on her this time."
    #hallway BG
    "After about a ten minute walk I’m close to giving up."
    "I can’t find her anywhere."
    "I thought I knew where the principal’s office was, but I can’t find that either."
    "Where could she be? Am I walking in circles?"
    "I suspect she’ll be back to get her books after she’s done doing... whatever it is she’s doing."
    "I’ll just wait in the classroom until she comes back..."
    "...And have myself a little nap."
    #goes to black, then show classroom BG
    "Something is staring at me."
    "I know this despite my face being buried in my folded arms on my desk - I can feel it."
    "Better find out who it is. I sit up."
    #Oni in
    oni "You’re still here?"
    "Well look at who finally showed up."
    oni "I hope you don’t actually sleep here, you must have a bed that’s much comfier to sleep in."
    oni "And that doesn't leave a big red mark on your face."
    "I rub the side of my face that had been pressed into my desk."
    kura "I was waiting for you."
    oni "Why would you do that?"
    "Maybe I went a little overboard. I feel like hours have passed."
    kura "Just wanted to see if you were okay."
    "She gives me a confused smile."
    oni "Of course I’m okay, silly. Was there something on your mind?"
    "Well..."
    "I just wanted to see if she was fine, really, but she seems confused about my worrying."
    kura "You looked like you were lost in thought earlier. My ears are always open for you if there's something on your mind, Oni."
    "At this, Oni looks like she’s trying to suppress a mild shock, as though she just remembered something horrifying."
    "She waves that reaction off in a flash and ducks her gaze."
    oni "...Yeah, I-"
    "She stops herself from finishing the sentence."
    "Eventually she faces me with a forced smile."
    oni "...I think that would be good. Can we go for a walk?"
    #hallway bg
    "We wander aimlessly around all the hallways for a while."
    "She’s avoided talking about what was worrying her earlier, but I don’t force anything out of her."
    "Maybe she just needs to work up the courage by talking about nonsensical topics first."
    oni "-so from that, I found out the books were written a while back. Isn’t that weird?"
    kura "Sure is, like, how could they predict things like that through dreams?"
    oni "Oh don’t misunderstand, they didn’t predict real life events. They created a whole new fictional world by just snoozing a lot."
    kura "Really? I want what they were on when they came up with that stuff."
    "Oni chuckles. It’s good to see she’s calmed down a bit."
    "We wander on."
    kura "Then again, I DO often have weird dreams of my own. I have no idea how my mind comes up with some of them."
    "Oni turns to me."
    oni "Oh? What are they like?"
    kura "I don't know if I should go into them too much, they really ARE weird-"
    oni "No, please do. I love hearing about things like this."
    "She interrupts me quickly and stares at me curiously. Almost too curiously - it's intense, and a little unnerving."
    kura "Well... Last night I was walking in some forest-like area. It didn’t feel like a normal forest at all, but like I was walking underwater..."
    oni "What were the colors like?"
    "That's a very specific question."
    kura "Hmm... Everything was very green and cyan, and the plants were glowing in these colors all around me."
    oni "...And how did it feel to walk there?"
    kura "...Weird. Calming but also worrying. There was nobody around, yet I didn’t feel like I was alone there."
    "Oni ponders over my answer. Maybe she's into dream theory?"
    "She keeps her worried frown and meets my eyes again."
    oni "What other dreams have you been having?"
    kura "Lemme think... Oh, I do remember a creepy one now."
    kura "I was with Kokoro who was trying to dig around for some magazine that had a recipe in it that she wanted to try. It was for a dish she had once but forgot what was in it."
    kura "She mentioned it was... Sweet? And that it was in a bowl? Pretty useless help, since a lot of sweet things can be put in a bowl, you know."
    kura "Anyway, she eventually stacks up about seven books and after a while we find something like the dish she remembered."
    kura "Here’s the thing though... The recipe was just a raw brain. A gross, slimy human brain in a fancy wooden bowl."
    kura "When I wanted to ask her what the H was her glitch, I was suddenly with Utagu at a completely different spot. Not for long though because I was so surprised that I woke myself up."
    kura "Wow, talking out loud about this feels weird. I hope you don’t-"
    "Oni violently grabs my shoulders, stopping me in my tracks."
    "She looks like she just heard me confessing to murder."
    "Why does she look so mad?"
    oni "...Kura, I’m about to ask you something that may not make any sense to you right now."
    "...No, not mad."
    "She looks absolutely terrified."
    oni "Do you..."
    "She takes a deep breath without breaking eye contact."
    oni "..."
    oni "...Do you remember me?"
    "...Huh?"
    kura "Of course I do- Oni, what is up with you?!"
    "I can’t shake her arms off. She’s buried her fingers into me like claws."
    oni "Think about it. Do you know who I am?"
    "I am too uncomfortable to say anything. I have no idea what’s going on."
    "She looks like she’s going to burst into tears any second."
    oni "Kura, please listen to me. I have to tell you something-"
    #quick flashes of other cryptic visions flash by in an instant
    "..."
    kura "...I..."
    kura "...I think I’m sick-"
    #cuts to black with a thud sound
return