label S_04_O:
    scene TESTSCENE with Dissolve(2.5)
    #black screen
    "...I feel like shit."
    #blurry classroom in
    "...Huh. I’m here again."
    "The others are here too."
    "I rub my eyes and look around."
    #bg in focus, girls are all there, music is probably muffled?
    "Here we are. At our usual spot. Wasting our time as always."
    "Were things always this quiet?"
    "I can’t hear a thing."
    "I feel mumbling noises in my ears, but no actual words that I understand are being said."
    kura "Hello?"
    "They don’t seem to hear me. They don’t see me, either."
    "Are they ignoring me?"
    kura "Is anyone listening to me?"
    "Nobody reacts to what I say. Have they gone deaf? Am I still dreaming?"
    "Before I become too angry I realize one eye has been on me since I woke up."
    #closeup of Oni
    "Why are you looking at me like that?"
    "Why won’t you talk to me?
    "Why the fuck won’t you acknowledge me?!"
    "Are you deaf?! Do you even have ears?!"
    #quick cut to cg of Oni’s hair being shoved to the sides by Kura, exposing her lack of ears
    oni "?!"
    kura "???"
    "Before I had time to think, I had lunged myself forward violently and shoved my arms at Oni’s face."
    "For a brief second, her face was completely exposed."
    #cut to bg with all girls
    "I saw it. I definitely saw it."
    "We all saw it."
    "How the hell is this possible?"
    "Oni looks at us like we were ghosts."
    "Nobody says a word, but at this point we all see and hear each other.
    "I feel my blood starting to boil."
    kura "Well? What do you have to say now?"
    "Oni seems absolutely terrified of me."
    kura "No words of wisdom from the all-knowing Oni?"
    "I take a step back."
    kura "Pity."
    "My voice is shaky."
    "The other girls look just as shocked as Oni, though they don’t seem so sure of who they are scared of."
    kura "You know, I’m sick of this bullshit, Oni. I am so, so sick of you looking over us like you just have to control everything. I don’t know what your deal is, or even what you are, but I’m fucking done."
    kura "I have absolutely no reason to trust anything you say anymore. You said things would be fine but look at what happened to Utagu! She turned into something I wouldn’t ever want to imagine in my worst nightmare!"
    utagu "Kura, stop this! I don’t know what you-"
    kura "SHUT UP!!"
    kura "See, SHE doesn’t even remember! Weird, huh? What great times we’ve shared together, huh?!"
    kura "Kokoro seeing fairies in the hallways but then pretends like it’s just sunny outside? Will she keep on twiddling her thumbs around as we all die?"
    kura "And who the HELL is Mei?! Is she the timeline fairy?"
    kura "Give me a FUCKING break."
    "I’m out of breath."
    "Nobody says a word."
    "I’m done."
    kura "Well since you all seem to have such a delightful time without me I’ll just go home for the day-"
    "But before I manage to walk too far, Oni grabs my arm quicker than lightning."
    "Her hand is shaking, but she has a firm grip of me."
    "I want to scream and rip her off of me, but the two words I hear before anything else..."
    oni "Don’t leave."
    "She pleads for me to stay. Huh, now she’s scared of letting me go?"
    "What a joke."
    kura "Oni, if you don’t take your fingers off me I WILL rip your skin off your pretty face."
    oni "It’s still out there. I’m begging you, don’t go. You’ll be hurt."
    kura "Wow, deciding to help me now. How noble. I’ll happily decline your words of wisdom this time."
    oni "You can stay here and yell at me all you want, beat me up as much as you wish, but PLEASE-"
    kura "LET GO OF ME YOU BITCH!!"
    "I finally manage to rip her off of me and dash out to the hallway."
    #cuts to black with sound fx
    "Before I even take my first step outside, something grabs me."
    "I can’t grab onto anything."
    "I’m being violently dragged to some unknown place."
    oni "KURA!"
    "I hear Oni scream for me. Her voice quickly fades as I’m being taken away."
    "Everything hurts."
    "It hurts."
    "It hurts."
    "The pain doesn’t stop."
    "Just before I think I can’t take any more, the creature has thrown me down some stairs. It then pushes me further into a room with such force that I almost break my spine."
    "I can’t move."
    "All I manage is to lift the side of my face to catch a glimpse of the thing that just abused me."
    #basement cg + shadow
    "...It’s that thing again."
    "I’ve seen it before, but..."
    "It wasn’t this big back then. It’s grown."
    "Whatever it is, the touch of it left me feeling so sick I could throw up."
    "The sickness exhausts my body completely."
    "I pass out."
    #blackness
    (no textbox, glitchy text in the beginning?) "...taking this matter over to th-"
    "-es, over there."
    "How is that one going? Any-"
    "...Huh. Ok, then switch them over to the other cage."
    "What about the Lelu? Will she manage the rest of this on her own?"
    "We can’t interfere too much more. Things are already spiraling out of control."
    "It’s risky, but we have to try."
    "I’m positive Oni can complete our mission this time."
