label S_05_O:
    scene TESTSCENE with Dissolve(2.5)
    "..."
    "..."
    "..."
    "..."
    #bg in, out of focus, all movements are very soft in this scene
    "...Again."
    "I’m here again."
    "We’re sitting here. Eating lunch. Just like always."
    #focus on Kokoro
    "Kokoro’s here, laughing her worries away. She probably wants to talk about a new movie she watched the other day. Maybe she’ll steal my food?"
    "I bet she will. Just like always."
    #Utagu in focus
    "Oh, Utagu. Will she ever stop letting her nerves get the better of her? I know how she always looks over her shoulders. What does she even think will be there?"
    "We will be there. Right with her."
    "Just like always."
    #pan to Oni
    "Oni. I don’t even remember if I was mad at you or not before but looking at you now feels like I might be able to believe in the normal old days."
    "Will you forgive me? Will you forget the awful things I said?"
    "Or did I even say anything at all?"
    "It feels like a memory I had that was never mine."
    "The old days..."
    "..."
    #kura sad sprite in, not showing the eyes
    "...I can’t stop the tears."
    "Everything feels so horrible."
    "I feel so alone."
    "I hate this. I hate this. I hate this."
    "Everything is wrong."
    "Their talking is drowned out by my uncontrollable sobbing."
    "I’m too weak for this."
    "The girls chatter on as I curl myself together to muffle the noise."
    "Then."
    (no textbox) "-ut! Cut that out!"
    "I hear a voice."
    (no textbox) "Oh yeah? So what if it is? We can do th-"
    "It cuts in and out, but I hear it clearly."
    "Have I finally lost it?"
    (no textbox) "-ay. Just leave her in there. It’s safe now. We-"
    "Do they know I can hear them?"
    kura "Hello?"
    (no textbox) "..?"
    "The voice stops talking as soon as I raise my voice."
    (no textbox) "You..."
    "I don’t know what to say to the voice. Too many questions come into my head."
    (no textbox) "Crap, I left the thing on again. We have to patch this up before-"
    "The voice stops abruptly."
    (no textbox) "...Kura. It’s nice to finally speak with you."
    "What?"
    kura "H-how do yo-"
    (no textbox) "I know a great deal about you, sweetheart. I’ve seen you go through so many horrible things, how much you’ve suffered and how you’re in pain as I’m speaking to you right now."
    (no textbox) "It’s a pity that the others aren’t as strong as you are. I don’t even know how things got so bad for them."
    kura "Who are you?! What are you doing to us?!"
    (no textbox) "Tsk, tsk, tsk... You can’t ask too many questions. You aren’t even supposed to know anything at all, yet here we are, talking because of a stupid mistake I made-"
    kura "What is wrong with you?! You’re completely inhumane, you just sit and laugh as I actually feel like my head will burst if I don’t understand what’s going on!"
    (no textbox) "Hm. That’s not good. I’ll get on that as soon as I fix that other problem to our right."
    "Their words make no sense to me, but my instinct tells me I should look to my right."
    #Oni_Shock in
    "I didn’t see it until now, but Oni has been fixated on me ever since I started talking to the voice."
    "Can she hear it too?"
    "She hasn’t said a word yet, but eventually opens her shaky lips."
    oni "...Stop this."
    (no textbox) "Oh? I thought our talks were to be private, Oni. Well, the more the merrier I guess, haha!"
    oni "Stop. This. Right. Now."
    "Oni isn’t talking to me."
    "She sounds like she’s threatening the voice talking to her."
    (no textbox) "What, feeling the pressure? You if anyone know I could just shut the whole thing down. I have my finger on the button right now."
    "Oni flinches violently and throws her desk to the side in a fit of rage."
    oni "DON’T YOU FUCKING DARE! DON’T TAKE HER AWAY FROM ME!"
    (no textbox) "Oni, you have been bad to us. Bad to the experiment. It’s the only way."
    oni "STOOOOOOOOOP!"
    #just when Oni’s line ends it immediately cuts everything to black